# Generated by Django 5.0.1 on 2026-01-31 07:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_tag", models.CharField(max_length=100, unique=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "model_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("warranty_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("in_repair", "In Repair"),
                            ("retired", "Retired"),
                            ("disposed", "Disposed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        help_text="Additional custom attributes as JSON",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "assets",
                "ordering": ["asset_tag"],
            },
        ),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "asset_types",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "db_table": "companies",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="ComponentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=100, unique=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        help_text="Type-specific attributes as JSON",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "component_types",
                "ordering": ["type_name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "locations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=255)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "vendors",
                "ordering": ["vendor_name"],
            },
        ),
        migrations.CreateModel(
            name="AssetRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requisition_number", models.CharField(max_length=100, unique=True)),
                (
                    "requisition_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("specifications", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("fulfilled_date", models.DateField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fulfilled_by_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilled_requisition",
                        to="propraetor.asset",
                    ),
                ),
                (
                    "asset_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisitions",
                        to="propraetor.assettype",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_requisitions",
                        to="propraetor.company",
                    ),
                ),
            ],
            options={
                "db_table": "asset_requisitions",
                "ordering": ["-requisition_date"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="propraetor.assetrequisition",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="propraetor.assettype",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="propraetor.company",
            ),
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "specifications",
                    models.TextField(
                        blank=True,
                        help_text="e.g., '16GB', '1TB', 'Intel i7-12700'",
                        null=True,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("warranty_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("installed", "Installed"),
                            ("spare", "Spare"),
                            ("failed", "Failed"),
                            ("removed", "Removed"),
                            ("disposed", "Disposed"),
                        ],
                        default="installed",
                        max_length=20,
                    ),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("removal_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="propraetor.asset",
                    ),
                ),
            ],
            options={
                "db_table": "components",
                "ordering": ["component_type", "manufacturer"],
            },
        ),
        migrations.CreateModel(
            name="ComponentRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requisition_number", models.CharField(max_length=100, unique=True)),
                (
                    "requisition_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "estimated_unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("specifications", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("fulfilled_date", models.DateField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_requisitions",
                        to="propraetor.company",
                    ),
                ),
                (
                    "fulfilled_by_component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilled_requisition",
                        to="propraetor.component",
                    ),
                ),
                (
                    "component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitions",
                        to="propraetor.componenttype",
                    ),
                ),
            ],
            options={
                "db_table": "component_requisitions",
                "ordering": ["-requisition_date"],
            },
        ),
        migrations.AddField(
            model_name="component",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="propraetor.componentrequisition",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="component_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="components",
                to="propraetor.componenttype",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="propraetor.company",
                    ),
                ),
                (
                    "default_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default location for users in this department",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_departments",
                        to="propraetor.location",
                    ),
                ),
            ],
            options={
                "db_table": "departments",
                "ordering": ["company", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AddField(
            model_name="componentrequisition",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="component_requisitions",
                to="propraetor.department",
            ),
        ),
        migrations.AddField(
            model_name="assetrequisition",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_requisitions",
                to="propraetor.department",
            ),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("extension", models.CharField(blank=True, max_length=20, null=True)),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="propraetor.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="propraetor.department",
                    ),
                ),
                (
                    "django_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="propraetor.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employees",
                "db_table": "users",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="componentrequisition",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="component_requisitions",
                to="propraetor.employee",
            ),
        ),
        migrations.CreateModel(
            name="ComponentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("installed", "Installed"),
                            ("removed", "Removed"),
                            ("replaced", "Replaced"),
                            ("upgraded", "Upgraded"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="propraetor.component",
                    ),
                ),
                (
                    "parent_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_history",
                        to="propraetor.asset",
                    ),
                ),
                (
                    "previous_component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_by",
                        to="propraetor.component",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="component_actions",
                        to="propraetor.employee",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Component histories",
                "db_table": "component_history",
                "ordering": ["-action_date"],
            },
        ),
        migrations.AddField(
            model_name="assetrequisition",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_requisitions",
                to="propraetor.employee",
            ),
        ),
        migrations.CreateModel(
            name="AssetDisposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disposal_date", models.DateField()),
                (
                    "disposal_method",
                    models.CharField(
                        choices=[
                            ("sold", "Sold"),
                            ("destroyed", "Destroyed"),
                            ("scrapped", "Scrapped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disposal_records",
                        to="propraetor.asset",
                    ),
                ),
                (
                    "disposed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disposed_assets",
                        to="propraetor.employee",
                    ),
                ),
            ],
            options={
                "db_table": "asset_disposal",
                "ordering": ["-disposal_date"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_assets",
                to="propraetor.employee",
            ),
        ),
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("returned_date", models.DateTimeField(blank=True, null=True)),
                ("condition_on_assignment", models.TextField(blank=True, null=True)),
                ("condition_on_return", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="propraetor.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_assignments",
                        to="propraetor.employee",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_assignments",
                        to="propraetor.location",
                    ),
                ),
            ],
            options={
                "db_table": "asset_assignments",
                "ordering": ["-assigned_date"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="propraetor.location",
            ),
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[("repair", "Repair"), ("upgrade", "Upgrade")],
                        max_length=20,
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("maintenance_date", models.DateField()),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="propraetor.asset",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_records",
                "ordering": ["-maintenance_date"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=100, unique=True)),
                ("invoice_date", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Cash, Card, Bank, Bkash",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID, receipt ID, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("received_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_invoices",
                        to="propraetor.company",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_invoices",
                        to="propraetor.employee",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="propraetor.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("component", "Component"),
                            ("service", "Service"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "item_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "asset_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_line_items",
                        to="propraetor.assettype",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_line_items",
                        to="propraetor.company",
                    ),
                ),
                (
                    "component_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_line_items",
                        to="propraetor.componenttype",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_line_items",
                        to="propraetor.department",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="propraetor.purchaseinvoice",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_line_items",
                "ordering": ["invoice", "line_number"],
                "unique_together": {("invoice", "line_number")},
            },
        ),
        migrations.AddField(
            model_name="componentrequisition",
            name="fulfilled_by_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfilled_component_requisitions",
                to="propraetor.purchaseinvoice",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="propraetor.purchaseinvoice",
            ),
        ),
        migrations.AddField(
            model_name="assetrequisition",
            name="fulfilled_by_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfilled_asset_requisitions",
                to="propraetor.purchaseinvoice",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="propraetor.purchaseinvoice",
            ),
        ),
        migrations.CreateModel(
            name="RequisitionFulfillment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requisition_type",
                    models.CharField(
                        choices=[("asset", "Asset"), ("component", "Component")],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_fulfilled",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset_requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillments",
                        to="propraetor.assetrequisition",
                    ),
                ),
                (
                    "component_requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillments",
                        to="propraetor.componentrequisition",
                    ),
                ),
                (
                    "invoice_line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillments",
                        to="propraetor.invoicelineitem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Requisition fulfillments",
                "db_table": "requisition_fulfillment",
            },
        ),
        migrations.CreateModel(
            name="SparePartsInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("specifications", models.TextField(blank=True, null=True)),
                (
                    "quantity_available",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantity_minimum",
                    models.IntegerField(
                        default=0,
                        help_text="Reorder threshold",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("last_restocked", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spare_parts",
                        to="propraetor.componenttype",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spare_parts",
                        to="propraetor.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Spare parts inventory",
                "db_table": "spare_parts_inventory",
            },
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["serial_number"], name="components_serial__eed433_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["asset_tag"], name="assets_asset_t_3d9023_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["serial_number"], name="assets_serial__240171_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["status"], name="assets_status_326766_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["company"], name="assets_company_916532_idx"),
        ),
    ]
