# Generated by Django 6.0.1 on 2026-01-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="zip",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="zip",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
