# Generated by Django 6.0.1 on 2026-01-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0002_company_zip_location_zip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
