# Generated by Django 6.0.1 on 2026-01-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0003_alter_employee_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
