# Generated by Django 6.0.1 on 2026-02-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0004_alter_employee_employee_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="zip",
            new_name="zipcode",
        ),
    ]
