# Generated by Django 6.0.1 on 2026-02-03 08:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0005_rename_zip_location_zipcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetrequisition",
            name="asset_type",
        ),
        migrations.RemoveField(
            model_name="assetrequisition",
            name="company",
        ),
        migrations.RemoveField(
            model_name="assetrequisition",
            name="department",
        ),
        migrations.RemoveField(
            model_name="assetrequisition",
            name="fulfilled_by_asset",
        ),
        migrations.RemoveField(
            model_name="assetrequisition",
            name="fulfilled_by_invoice",
        ),
        migrations.RemoveField(
            model_name="assetrequisition",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="componentrequisition",
            name="company",
        ),
        migrations.RemoveField(
            model_name="componentrequisition",
            name="component_type",
        ),
        migrations.RemoveField(
            model_name="componentrequisition",
            name="department",
        ),
        migrations.RemoveField(
            model_name="componentrequisition",
            name="fulfilled_by_component",
        ),
        migrations.RemoveField(
            model_name="componentrequisition",
            name="fulfilled_by_invoice",
        ),
        migrations.RemoveField(
            model_name="componentrequisition",
            name="requested_by",
        ),
        migrations.CreateModel(
            name="Requisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requisition_number", models.CharField(max_length=100, unique=True)),
                (
                    "requisition_type",
                    models.CharField(
                        choices=[("asset", "Asset"), ("component", "Component")],
                        max_length=20,
                    ),
                ),
                (
                    "requisition_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("specifications", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "estimated_unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("fulfilled_date", models.DateField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisitions",
                        to="propraetor.assettype",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitions",
                        to="propraetor.company",
                    ),
                ),
                (
                    "component_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisitions",
                        to="propraetor.componenttype",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitions",
                        to="propraetor.department",
                    ),
                ),
                (
                    "fulfilled_by_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilled_requisitions",
                        to="propraetor.asset",
                    ),
                ),
                (
                    "fulfilled_by_component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilled_requisitions",
                        to="propraetor.component",
                    ),
                ),
                (
                    "fulfilled_by_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilled_requisitions",
                        to="propraetor.purchaseinvoice",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitions",
                        to="propraetor.employee",
                    ),
                ),
            ],
            options={
                "db_table": "requisitions",
                "ordering": ["-requisition_date"],
            },
        ),
        migrations.AddField(
            model_name="requisitionfulfillment",
            name="requisition",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fulfillments",
                to="propraetor.requisition",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asset",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="propraetor.requisition",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="propraetor.requisition",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requisitionfulfillment",
            unique_together={("requisition", "invoice_line_item")},
        ),
        migrations.AddIndex(
            model_name="requisitionfulfillment",
            index=models.Index(
                fields=["requisition", "created_at"],
                name="requisition_requisi_5a94ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="requisition",
            index=models.Index(
                fields=["requisition_type", "status"],
                name="requisition_requisi_91254e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="requisition",
            index=models.Index(
                fields=["company", "department"], name="requisition_company_40a7ad_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="requisitionfulfillment",
            name="asset_requisition",
        ),
        migrations.RemoveField(
            model_name="requisitionfulfillment",
            name="component_requisition",
        ),
        migrations.RemoveField(
            model_name="requisitionfulfillment",
            name="requisition_type",
        ),
        migrations.DeleteModel(
            name="AssetRequisition",
        ),
        migrations.DeleteModel(
            name="ComponentRequisition",
        ),
    ]
