# Generated by Django 6.0.1 on 2026-02-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0006_remove_assetrequisition_asset_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank for custom builds or unknown",
                        max_length=255,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="e.g., '15', 'Satellite Pro C40-G', 'Custom', 'Unidentified'",
                        max_length=255,
                    ),
                ),
                (
                    "model_number",
                    models.CharField(
                        blank=True,
                        help_text="Official model/part number from manufacturer",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="General notes (common issues, EOL date, warranty period, etc.)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "asset_models",
                "ordering": ["manufacturer", "model_name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="asset",
            name="asset_type",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="asset_type",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="model",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="model_number",
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("active_assigned", "Assigned"),
                    ("in_repair", "In Repair"),
                    ("retired", "Retired"),
                    ("disposed", "Disposed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="propraetor.assetmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="asset_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_line_items",
                to="propraetor.assetmodel",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["asset_model"], name="assets_asset_m_67020c_idx"
            ),
        ),
        migrations.AddField(
            model_name="assetmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="models",
                to="propraetor.category",
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="asset_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requisitions",
                to="propraetor.category",
            ),
        ),
        migrations.AddIndex(
            model_name="assetmodel",
            index=models.Index(
                fields=["manufacturer", "model_name"],
                name="asset_model_manufac_cda2a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetmodel",
            index=models.Index(
                fields=["category"], name="asset_model_categor_bc021c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetmodel",
            constraint=models.UniqueConstraint(
                fields=("category", "manufacturer", "model_name"),
                name="unique_model_per_category",
            ),
        ),
        migrations.DeleteModel(
            name="AssetType",
        ),
    ]
