# Generated by Django 6.0.1 on 2026-02-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0007_assetmodel_category_remove_asset_asset_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("in_repair", "In Repair"),
                    ("retired", "Retired"),
                    ("disposed", "Disposed"),
                    ("inactive", "Inactive"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="specifications",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
