# Generated by Django 6.0.1 on 2026-02-07 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("propraetor", "0008_alter_asset_status_alter_requisition_specifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("requisition", "Requisition"),
                            ("invoice", "Invoice"),
                            ("assignment", "Assignment"),
                            ("component", "Component"),
                            ("user", "User"),
                            ("company", "Company"),
                            ("location", "Location"),
                            ("department", "Department"),
                            ("vendor", "Vendor"),
                            ("category", "Category"),
                            ("asset_model", "Asset Model"),
                            ("component_type", "Component Type"),
                            ("spare_part", "Spare Part"),
                            ("maintenance", "Maintenance"),
                            ("disposal", "Disposal"),
                            ("line_item", "Line Item"),
                            ("fulfillment", "Fulfillment"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("assigned", "Assigned"),
                            ("unassigned", "Unassigned"),
                            ("status_changed", "Status Changed"),
                            ("duplicated", "Duplicated"),
                            ("approved", "Approved"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                            ("activated", "Activated"),
                            ("deactivated", "Deactivated"),
                            ("bulk_deleted", "Bulk Deleted"),
                            ("bulk_status", "Bulk Status Change"),
                            ("paid", "Marked Paid"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="Human-readable summary, e.g. 'Asset LAPTOP-042 created'.",
                        max_length=512,
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Secondary info, e.g. status display or assignee name.",
                        max_length=512,
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Snapshot of actor display name at time of event.",
                        max_length=255,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "object_repr",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("url", models.CharField(blank=True, default="", max_length=512)),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="Optional JSON dict of changed fields, e.g. {'status': ['active', 'retired']}.",
                        null=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log Entry",
                "verbose_name_plural": "Activity Log",
                "db_table": "activity_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "-timestamp"],
                        name="activity_lo_event_t_d5900f_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="activity_lo_content_c82b76_idx",
                    ),
                ],
            },
        ),
    ]
