# Generated by Django 6.0.1 on 2026-02-07 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0009_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved the requisition.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_requisitions",
                to="propraetor.employee",
            ),
        ),
    ]
