# Generated by Django 6.0.1 on 2026-02-07 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0010_requisition_approved_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequisitionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("asset", "Asset"), ("component", "Component")],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "requisition_items",
                "ordering": ["requisition", "created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="requisitionfulfillment",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="requisitionfulfillment",
            name="requisition_requisi_5a94ed_idx",
        ),
        migrations.RemoveIndex(
            model_name="requisition",
            name="requisition_requisi_91254e_idx",
        ),
        migrations.AddIndex(
            model_name="requisition",
            index=models.Index(
                fields=["status", "priority"], name="requisition_status_52160e_idx"
            ),
        ),
        migrations.AddField(
            model_name="requisitionitem",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisition_items",
                to="propraetor.asset",
            ),
        ),
        migrations.AddField(
            model_name="requisitionitem",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisition_items",
                to="propraetor.component",
            ),
        ),
        migrations.AddField(
            model_name="requisitionitem",
            name="invoice_line_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requisition_items",
                to="propraetor.invoicelineitem",
            ),
        ),
        migrations.AddField(
            model_name="requisitionitem",
            name="requisition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="propraetor.requisition",
            ),
        ),
        migrations.RemoveField(
            model_name="requisitionfulfillment",
            name="invoice_line_item",
        ),
        migrations.RemoveField(
            model_name="requisitionfulfillment",
            name="requisition",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="asset_type",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="component_type",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="estimated_unit_cost",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="fulfilled_by_asset",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="fulfilled_by_component",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="fulfilled_by_invoice",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="requisition_type",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="total_estimated_cost",
        ),
        migrations.AddIndex(
            model_name="requisitionitem",
            index=models.Index(
                fields=["requisition", "created_at"],
                name="requisition_requisi_a2a7f4_idx",
            ),
        ),
        migrations.DeleteModel(
            name="RequisitionFulfillment",
        ),
    ]
