# Generated by Django 6.0.1 on 2026-02-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0011_remake_requisition_system"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssetDisposal",
        ),
    ]
