# Generated by Django 6.0.1 on 2026-02-07 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0012_remove_asset_disposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="invoice_line_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific invoice line item this asset was purchased under.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="propraetor.invoicelineitem",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="invoice_line_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific invoice line item this component was purchased under.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="propraetor.invoicelineitem",
            ),
        ),
        migrations.AddField(
            model_name="requisition",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Invoice that fulfills this requisition.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requisitions",
                to="propraetor.purchaseinvoice",
            ),
        ),
    ]
