# Generated by Django 6.0.1 on 2026-02-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0014_component_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_tag",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for this asset (auto-generated if left blank).",
                max_length=100,
                unique=True,
            ),
        ),
    ]
