# Generated by Django 6.0.1 on 2026-02-08 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0015_asset_tag_auto_generate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requisition",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="requisitionitem",
            name="invoice_line_item",
        ),
        migrations.AlterField(
            model_name="requisition",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional – person who approved this requisition.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_requisitions",
                to="propraetor.employee",
            ),
        ),
    ]
