# Generated by Django 5.2.11 on 2026-02-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propraetor', '0017_alter_asset_serial_number_alter_company_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('assigned_to__isnull', False), ('location__isnull', False), _negated=True), name='asset_not_assigned_to_both'),
        ),
    ]
