# Generated by Django 5.2.11 on 2026-02-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propraetor", "0018_location_updated_at_asset_asset_not_assigned_to_both"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
